authors:
    mdevaev:
        name: Maxim Devaev
        description: Software Shaman
        avatar: https://avatars.githubusercontent.com/u/416259
        url: https://github.com/mdevaev
    yar:
        name: Iaroslav Liachin
        description: Hardware Engineer
        avatar: https://avatars.githubusercontent.com/u/88896544
        url: https://github.com/Amt921
