name: ci 

on:
  push:
    branches: 
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-video markdown-include
      - run: mkdocs gh-deploy --force
